[project]
name = "pitmon"
version = "0.4.0"
requires-python = ">=3.9"
dependencies = ["numpy"]

[project.optional-dependencies]
dev = ["pytest>=7.0"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
